### PR TITLE
Fix

### PR DESCRIPTION
**Pull request by arikarim**
we created a branch called "fix" for the development of the application.
On the initial commit, we created a basic structure for the page and added CDN links Font awesome, set up linter configured it and I also added Google Fonts.
"Mobile first" approach is used in order to achieve responsiveness principles.
Elements are positioned using grid, flex and positioning techniques.
The issues raised from the first review of the project in the dashboard are fully addressed.

Please review my project before I merge my branch.
Thanks in advance!

### CODE REVIEW

**Comment by mimipeshy** [comment]
### STATUS :CHANGES REQUIRED :red_circle: :recycle: 

Hello @arikarim and @tta2yta :wave: :wave: , good job on working on this project. Your page is similar to the clone, keep it up :clap: However, to make it perfect, some changes are needed

#### Mobile View

- [ ] Content take 100% of the screen width size. Kindly check on it

**Original**
image
**Clone**
image

- [ ] I believe you are using very large screens which makes the breakpoints different from normal screen sizes. The following are the recommended screen sizes for this project :smile: 
- No small breakpoint as it is mobile first and the base styles are for the mobile screen
- medium: min-width around 768px
- large: min-width 1024px

- [ ] Lets clean up the CSS. For example `display:flex` is repeated 11 times. It breaks the DRY rule. For the repeating CSS properties, you can create one CSS class for it eg `d-flex: flex` then use the class whenever possible. Refer to this [link](https://meiert.com/en/blog/dry-css/) for more readings


That's all :smile: , kindly submit another review when done.

_Feel free to reach out to me on slack if you have any questions or something is unclear, I will be glad to help_
Regards
Peris Ndanu

**Comment by tta2yta** [comment]
Hello. Thank you for your code reviews. We have corrected the points you mentioned. could you please make a code review again?

**Review by jubaan — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

There are some issues that need to be addressed before we can move forward. Please review the list below.

## Required changes :wrench: 
### [Mandatory] :red_circle: 

- [ ] The breakpoint are not matching correctly
  - [ ] Tablet view from 768 to 1023.99 (right now goes from 769 to 1024)
  - [ ] Desktop view from 1024 and up (the same as above happens here)

- [ ] Tablet view is creating a wit space to the side of the website
image

- [ ] Please review the CSS stylesheet as it still has other rules that are widely repeated. to mention some: `position: absolute`, `display: none`. As you have done with `display: flex` work with this and other repeated code that you can find.

## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

**Comment by arikarim** [comment]
we fixed the tablet mode responsivness and other stuff ,, please have a look,.

**Review by ebeagusamuel — APPROVED** [review]
# Project Approved :100: 
### Hey there :wave: 
#### Congratulations, this project is now approved. You have made the changes requested by the last reviewer and you can now go ahead and merge this branch and move to the next project.
#### P.S: In your subsequent projects, do not commit node_modules to GitHub or any other repository. You need to add them to your gitignore file.
slack(@ebeagusamuel)

**Comment by tta2yta** [comment]
Hello. Thank you very much for your time and help.

Respectfully yours.

**Pull request merged**
